global:
  scrape_interval: 0s250ms
  scrape_timeout: 0s250ms
  evaluation_interval: 10s
scrape_configs:
- job_name: prometheus-mtt
  honor_timestamps: true
  scrape_interval: 0s250ms
  scrape_timeout: 0s250ms
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:19501